sources:
    - name: postgres
      description: This is a replica of the Postgres database used by our app
      database: eco-rune-459817-m9
      schema: raw_pay
      tables:
          - name: orders
          - name: users
          - name: transactions
          - name: refunds
          - name: methods
